//created on: May 26, 2015
package com.bnymellon.rules

//list any import classes here.



//declare any global variables here



rule "Your First Rule"

	when r : Router (routetype == "Function" )
		then 
					r.setDestinationType("Group" );
	     	        r.setDestination( "Corporate Actions Brussels" );

end


rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
